import { createKnownValueIndex } from './known-values.mjs';
import { redactPatterns } from './residual-scan.mjs';

const MAX_LINES = 500;
const MAX_COLUMNS = 16;
const MAX_CHARS = 50000;
const ALIASES = 'MEDICAL RECORD NUMBER|ACCESSION NUMBER|ACCOUNT NUMBER|ORDER NUMBER|PATIENT NAME|PATIENT ID|MEDICAL RECORD|DATE OF BIRTH|BIRTH DATE|VISIT DATE|STUDY DATE|PHYSICIAN|PROVIDER|FACILITY|INSTITUTION|HOSPITAL|CLINIC|ACCESSION|PATIENTID|PATIENT|ENCOUNTER|TELEPHONE|CONTACT|ADDRESS|ACCOUNT|ORDER|DOCTOR|PHONE|E-MAIL|EMAIL|NAME|MRN|DOB|ACC'
  .split('|').map(label => label.replaceAll(' ', '[\\s_-]+')).join('|');
